export type Competition = {
  id: string;
  title: string;
  subtitle: string;
  branch: string;
  studyForm: string;
  educationLevel: string;
  basis: string;
  seats: number;
  url: string;
};

export const competitions: Competition[] = [
  {
    id: 'psychology-fulltime',
    title: '37.03.01 — Психология',
    subtitle: 'Социальная киберпсихология и искусственный интеллект',
    branch: 'Минск',
    studyForm: 'Очная',
    educationLevel: 'Бакалавриат',
    basis: 'Бюджет',
    seats: 8,
    url: 'https://pk.rgsu.net/competition/832a62dc-f07a-11f0-b35d-f4034344acdb',
  },
  {
    id: 'psychology-parttime',
    title: '37.03.01 — Психология',
    subtitle: 'Социальная киберпсихология и искусственный интеллект',
    branch: 'Минск',
    studyForm: 'Очно-заочная',
    educationLevel: 'Бакалавриат',
    basis: 'Бюджет',
    seats: 4,
    url: 'https://pk.rgsu.net/competition/cf01a63b-f07a-11f0-b35d-f4034344acdb',
  },
  {
    id: 'management-fulltime',
    title: '38.03.02 — Менеджмент',
    subtitle: 'Менеджмент и маркетинг в цифровой среде',
    branch: 'Минск',
    studyForm: 'Очная',
    educationLevel: 'Бакалавриат',
    basis: 'Бюджет',
    seats: 16,
    url: 'https://pk.rgsu.net/competition/3ebfdc93-f07b-11f0-b35d-f4034344acdb',
  },
  {
    id: 'social-work-fulltime',
    title: '39.03.02 — Социальная работа',
    subtitle: 'Специалист по комплексной реабилитации',
    branch: 'Минск',
    studyForm: 'Очная',
    educationLevel: 'Бакалавриат',
    basis: 'Бюджет',
    seats: 8,
    url: 'https://pk.rgsu.net/competition/b90f9726-f07b-11f0-b35d-f4034344acdb',
  },
  {
    id: 'social-work-parttime',
    title: '39.03.02 — Социальная работа',
    subtitle: 'Специалист по комплексной реабилитации',
    branch: 'Минск',
    studyForm: 'Заочная',
    educationLevel: 'Бакалавриат',
    basis: 'Бюджет',
    seats: 8,
    url: 'https://pk.rgsu.net/competition/0d59f6cc-f07c-11f0-b35d-f4034344acdb',
  },
  {
    id: 'law-fulltime',
    title: '40.03.01 — Юриспруденция',
    subtitle: 'Гражданско-правовая',
    branch: 'Минск',
    studyForm: 'Очная',
    educationLevel: 'Бакалавриат',
    basis: 'Бюджет',
    seats: 8,
    url: 'https://pk.rgsu.net/competition/7023ede3-f07c-11f0-b35d-f4034344acdb',
  },
  {
    id: 'psychology-fulltime-contract',
    title: '37.03.01 — Психология',
    subtitle: 'Социальная киберпсихология и искусственный интеллект',
    branch: 'Минск',
    studyForm: 'Очная',
    educationLevel: 'Бакалавриат',
    basis: 'Платное',
    seats: 55,
    url: 'https://pk.rgsu.net/contest/b3af3dae-f07a-11f0-b35d-f4034344acdb',
  },
  {
    id: 'psychology-parttime-contract',
    title: '37.03.01 — Психология',
    subtitle: 'Социальная киберпсихология и искусственный интеллект',
    branch: 'Минск',
    studyForm: 'Очно-заочная',
    educationLevel: 'Бакалавриат',
    basis: 'Платное',
    seats: 59,
    url: 'https://pk.rgsu.net/contest/f768ca58-f07a-11f0-b35d-f4034344acdb',
  },
  {
    id: 'management-fulltime-contract',
    title: '38.03.02 — Менеджмент',
    subtitle: 'Менеджмент и маркетинг в цифровой среде',
    branch: 'Минск',
    studyForm: 'Очная',
    educationLevel: 'Бакалавриат',
    basis: 'Платное',
    seats: 45,
    url: 'https://pk.rgsu.net/contest/6a5835a0-f07b-11f0-b35d-f4034344acdb',
  },
  {
    id: 'social-work-fulltime-contract',
    title: '39.03.02 — Социальная работа',
    subtitle: 'Специалист по комплексной реабилитации',
    branch: 'Минск',
    studyForm: 'Очная',
    educationLevel: 'Бакалавриат',
    basis: 'Платное',
    seats: 38,
    url: 'https://pk.rgsu.net/contest/e97c1cf2-f07b-11f0-b35d-f4034344acdb',
  },
  {
    id: 'social-work-parttime-contract',
    title: '39.03.02 — Социальная работа',
    subtitle: 'Специалист по комплексной реабилитации',
    branch: 'Минск',
    studyForm: 'Заочная',
    educationLevel: 'Бакалавриат',
    basis: 'Платное',
    seats: 62,
    url: 'https://pk.rgsu.net/contest/44f67a27-f07c-11f0-b35d-f4034344acdb',
  },
  {
    id: 'law-fulltime-contract',
    title: '40.03.01 — Юриспруденция',
    subtitle: 'Гражданско-правовая',
    branch: 'Минск',
    studyForm: 'Очная',
    educationLevel: 'Бакалавриат',
    basis: 'Платное',
    seats: 55,
    url: 'https://pk.rgsu.net/contest/992399ae-f07c-11f0-b35d-f4034344acdb',
  },
];
